import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans, Quicksand } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/common/Appsidebar";
import { cookies } from "next/headers";

const playfairDisplayHeading = Quicksand({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["300", "400", "500", "600", "700"],
});

const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const defaultLinks = [{ name: "Projects", href: "/dashboard" }];

  const authLinks = [{ name: "Settings", href: "/settings" }];
  const guestLinks = [
    { name: "Login", href: "/login" },
    { name: "Register", href: "/register" },
  ];
  const footerLinks = [
    {
      title: "Product",
      links: [
        { name: "Dashboard", href: "/dashboard" },
        { name: "Features", href: "/features" },
      ],
    },
    {
      title: "Company",
      links: [
        { name: "About", href: "/about" },
        { name: "Contact", href: "/contact" },
      ],
    },
    {
      title: "Legal",
      links: [
        { name: "Privacy", href: "/privacy" },
        { name: "Terms", href: "/terms" },
      ],
    },
  ];
  const cookieStore = await cookies();
  const isAuth = !!cookieStore.get("access_token");
  const links = isAuth
    ? defaultLinks.concat(authLinks)
    : defaultLinks.concat(guestLinks);

  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        notoSans.variable,
        playfairDisplayHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <SidebarProvider defaultOpen={false}>
          <div className="w-screen">
            <Header links={links} isAuth={isAuth} />

            {children}
            <AppSidebar links={links} isAuth={isAuth} />
            <Footer groups={footerLinks} />
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
