"""added citations to messages

Revision ID: aaf0d3f3613c
Revises: f055cb6c1a9d
Create Date: 2026-10-01 16:19:24.244928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf0d3f3613c'
down_revision: Union[str, Sequence[str], None] = 'f055cb6c1a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'chunk_id')
    )
    op.drop_constraint(op.f('messages_reference_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'reference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_reference_id_fkey'), 'messages', 'chunks', ['reference_id'], ['id'], ondelete='SET NULL')
    op.drop_table('citations')
    # ### end Alembic commands ###
